package com.abantohq.weddingplanner.usermanagement;

public enum WedRole {
  GROOM,
  BRIDE,
  MARCHING,
  WAYBEARER,
  USHER,
  MATRON,
  BRIDESMAID,
  GROOMSMEN,
  GROOMSPARENT,
  BRIDESPARENT,
  GROOMSGUEST,
  BRIDESGUEST,
  GROOMSGUEST_PLUSONE,
  BRIDESGUEST_PLUSONE,
  GUEST,
  OFFICIATING_MINISTER,
  OFFICIATING_SUPPORT,
  VENDOR
}
